### ISSUE TITLE
I can't find class

### ISSUE THREAD

**Issue by TheDevTec** [MadMartian/hydrazine-path-finding#1]
I have eclipse error "The type com.extollit.linalg.immutable.AxisAlignedBBox cannot be resolved. It is indirectly referenced from required .class files"
I can't seem to find where should i import this class from, also i cannot use Maven or Gradle, only Jars.
Could you please point me to the dependency?

**Comment by MadMartian** [comment]
Try adding _data-structures_ to your `build.gradle` as a dependency: 
`compile group: 'com.github.MadMartian', name: 'data-structures', version: '2.9'`
