### ISSUE TITLE
2D Usage

### ISSUE THREAD

**Issue by DrOreo002** [MadMartian/hydrazine-path-finding#3]
Hey, do you have any working example for 2d world usage? I kinda struggled to get it working

**Comment by MadMartian** [comment]
No working example, no... you could definitely achieve this though by how you implement the columnar spaces, which report where the "blocks" (solid ground / obstacles etc) are.  I would achieve this by pretending the world exists at y-level 64, no higher, no lower, except for obstacles you will want to make them at least two "blocks" high reaching to y-level 68.
